services:
  storefront:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SALEOR_API_URL: ${NEXT_PUBLIC_SALEOR_API_URL}
        NEXT_PUBLIC_STOREFRONT_URL: ${NEXT_PUBLIC_STOREFRONT_URL}
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_DEFAULT_CHANNEL: ${NEXT_PUBLIC_DEFAULT_CHANNEL}
      # передадим в рантайм (если нужен)
      SALEOR_APP_TOKEN: ${SALEOR_APP_TOKEN:-}
    ports:
      - "3000:3000"
    restart: unless-stopped
